version: '2'
services:
  postgres:
    build:
      context: ./db
    ports:
      - "5432:5432"
  hibernate:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    links:
      - postgres:postgres